FROM node:alpine

WORKDIR /app

COPY package.json .

RUN npm install

# We technically do not need to copy everything over if we're using volumes
# But it is good practice
COPY . .

CMD ["npm", "run", "start"]
